## remain:
## Pacman mirrors
## Lable all tools
## Printer
## Set zsh as user's login shell

- name: Create User sensei
  hosts: all
  become: true
  vars_files: [vars.yml]
  tags: [always]
  tasks:
    - name: Include create user task
      import_tasks: ansible/tasks/createuser/create-user.yaml

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: "sshd"
        enabled: yes
        state: "restarted"
        sleep: 5

## Initial setup for arch role
- name: Initial Setup
  hosts: all
  become: true
  vars_files: [vars.yml]
  tags: [always, init]
  tasks:
    - name: Include initial setup task
      when: ansible_os_family == 'Archlinux'
      import_tasks: ansible/tasks/initsetup/arch.yaml

  handlers:
    - name: Update grub
      ansible.builtin.command: update-grub

## osqueryd role
- name: Osqueryd
  hosts: all
  become: true
  tags: [always, osquery, osqueryd]
  vars_files: [vars.yml]
  tasks:
    - name: Run osquery role
      include_role:
        name: ansible-osquery

## SSSD role
- name: SSSD
  hosts: all
  become: true
  tags: [always, sssd]
  vars_files: [vars.yml]
  tasks:
    - name: Run SSSD role
      include_role:
        name: ansible-role-sssd

## security hardening role
- name: Security-hardening
  hosts: all
  become: true
  tags: [always, security-hardening]
  vars_files: [vars.yml]
  tasks:
    - name: Run security-hardening role
      include_role:
        name: ansible-role-security-hardening
