devops_pacman:
  [
    helm,
    doctl,
    openldap,
    ansible,
    epiphany,
    tree,
    podman,
    skopeo,
    aws-cli,
    terraform,
    epiphany, ## for accessing non HSTS
  ]

devops_yay:
  [
    k9,
    ngrok,
    dive,
    concourse-fly-bin,
    fluxctl,
    google-cloud-sdk,
    lazydocker-bin,
    github-cli,
  ]
