essential_pacman:
  [
    jq,
    alacritty,
    baobab,
    base-devel,
    docker,
    docker-compose,
    fakeroot,
    fasd,
    feh,
    firefox,
    flameshot,
    git,
    gitui,
    htop,
    m4,
    make,
    nethogs,
    openssh,
    patch,
    peek,
    samba,
    simple-scan,
    synapse,
    tk,
    vim,
    vlc,
    xclip,
    zsh,
    htop,
    python,
    python-pip,
    tree,
    ufw,
    osquery=5.0.1,
    iputils, ## for ping
    bind, ## For dig
  ]

essential_yay:
  [
    brother-mfc-7860dw,
    brscan4,
    gitflow-avh,
    google-chrome,
    peazip-qt-bin,
    rslsync,
    slack-desktop,
    sublime-text-4,
    ttf-ms-fonts,
  ]
