---
# - name: Print the gateway for each host when defined
#   ansible.builtin.debug:
#     msg: "{{ testing }}"

# tasks file for sssd
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-archlinux.yml
  when: ansible_os_family == 'Archlinux'

- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: common.yml
